version: '3'
services:
  mysql_maestro1:
    image: mysql:5.7
    container_name: maestro1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3310:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica --auto-increment-increment=2 --auto-increment-offset=1
    networks:
      - mysql_cluster
    volumes:
      - maestro1-data:/var/lib/mysql

  mysql_maestro2:
    image: mysql:5.7
    container_name: maestro2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3307:3306"
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica --auto-increment-increment=2 --auto-increment-offset=2
    networks:
      - mysql_cluster
    volumes:
      - maestro2-data:/var/lib/mysql

  phpmyadmin1:
    image: phpmyadmin
    container_name: phpmyadmin1
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "mysql_maestro1"
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "http://localhost:8081/"
    networks:
      - mysql_cluster

  phpmyadmin2:
    image: phpmyadmin
    container_name: phpmyadmin2
    ports:
      - "8082:80"
    environment:
      PMA_HOST: "mysql_maestro2"
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "http://localhost:8082/"
    networks:
      - mysql_cluster

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mysql_cluster

volumes:
  maestro1-data:
  maestro2-data:

networks:
  mysql_cluster:
